name: 'dbt_rmaffioli'
version: '1.0.0'
config-version: 2

profile: 'dbt_rmaffioli'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  pricing_compare_date_past: '2021-07-12'
  pricing_compare_date_recent: '2022-07-11'

models:
  dbt_rmaffioli:
    +persist_docs:
      relation: true
      columns: true

    staging:
      +materialized: view
      +schema: staging
      stg_calendar:
        +materialized: table

    intermediate:
      +materialized: table
      +schema: intermediate

    marts:
      core:
        +materialized: table
        +schema: core
        dim_listings:
          +materialized: view
      reporting:
        +materialized: table
        +schema: reporting
